# Generated by Django 2.0.4 on 2018-05-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0005_auto_20180509_0902'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunausers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc1', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc10', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc2', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc3', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc4', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc5', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc6', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc7', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc8', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='soc9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc9', to='Uni_Socs.Universities_Societies'),
        ),
        migrations.AddField(
            model_name='lunausers',
            name='uni_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Uni_Socs.Universities'),
        ),
    ]
