# Generated by Django 2.0.4 on 2018-05-11 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0009_auto_20180511_0756'),
        ('Users', '0003_auto_20180509_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP_yes_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Uni_Socs.Events')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.LunaUsers')),
            ],
        ),
    ]
