# Generated by Django 2.0.4 on 2018-05-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0013_auto_20180512_0740'),
        ('Users', '0004_rsvp_yes_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVP_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Uni_Socs.Events')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.LunaUsers')),
            ],
        ),
        migrations.RemoveField(
            model_name='rsvp_yes_event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='rsvp_yes_event',
            name='user',
        ),
        migrations.DeleteModel(
            name='RSVP_yes_event',
        ),
    ]
