# Generated by Django 2.0.4 on 2018-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_lunausers_security_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunausers',
            name='verification_status',
            field=models.CharField(default='unverified', max_length=10),
        ),
        migrations.AlterField(
            model_name='lunausers',
            name='security_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
