# Generated by Django 2.0.4 on 2018-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20180517_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunausers',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='lunausers',
            name='verification_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
