# Generated by Django 2.0.4 on 2018-05-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='domain',
            field=models.CharField(default='@test_uni.com', max_length=30),
        ),
    ]
