# Generated by Django 2.0.4 on 2018-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0003_universities_societies'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities_societies',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
