# Generated by Django 2.0.4 on 2018-05-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0004_universities_societies_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universities_societies',
            old_name='from_uni',
            new_name='uni_fk',
        ),
    ]
