# Generated by Django 2.0.4 on 2018-05-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0005_auto_20180509_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='uni_facebook_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
