# Generated by Django 2.0.4 on 2018-05-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0006_universities_uni_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities_societies',
            name='fb_id',
            field=models.CharField(default='NO ID PRESENT', max_length=100),
        ),
    ]
