# Generated by Django 2.0.4 on 2018-05-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0007_universities_societies_fb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('address', models.CharField(max_length=300)),
                ('tickets', models.BooleanField(default=False)),
                ('details', models.TextField(max_length=100000)),
                ('uni_socs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Uni_Socs.Universities_Societies')),
            ],
        ),
    ]
