# Generated by Django 2.0.4 on 2018-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0011_auto_20180511_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='tickets',
            field=models.CharField(max_length=300),
        ),
    ]
