# Generated by Django 2.0.4 on 2018-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0014_auto_20180514_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities_societies',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
