# Generated by Django 2.0.4 on 2018-05-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0015_universities_societies_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='published_date',
        ),
    ]
