# Generated by Django 2.0.4 on 2018-05-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uni_Socs', '0016_remove_events_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
